Repository eawiggans/bubble-up, pull requests merged in 2023-02, with the labels that each got.

#23 Home Page Set Up
  client/src/pages/Home.js
Labels: new feature

#25 Resolvers and TypeDefs
  client/package.json
  server/models/Difficulty.js
  server/models/Question.js
  server/models/QuestionType.js
  server/models/Score.js
  server/models/index.js
  server/package-lock.json
  server/package.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/utils/auth.js
Labels: enhancement

#27 Feature/quiz
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Algorithm/Button.jsx
  client/src/components/Algorithm/CodeEditorWindow.jsx
  client/src/components/Algorithm/Editor.jsx
  client/src/components/Algorithm/Landing.jsx
  client/src/components/MultChoice/MultChoice.jsx
  client/src/pages/Home.js
  client/src/pages/Quiz.js
Labels: enhancement

#32 Feature/quiz
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Algorithm/Algorithm.jsx
  client/src/components/Algorithm/Button.jsx
  client/src/components/Algorithm/CodeEditorWindow.jsx
  client/src/components/Algorithm/Editor.jsx
  client/src/components/Algorithm/Landing.jsx
  client/src/components/Blog/QuestionsList.jsx
  client/src/components/Blog/SingleQuestion.jsx
  client/src/components/MultChoice/MultChoice.jsx
  client/src/components/Navbar/Navbar.js
  client/src/components/TextArea/TextArea.jsx
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/Quiz.js
  client/src/pages/Signup.js
  client/src/utils/auth.js
  client/src/utils/mutations.js
  server/models/User.js
  server/package-lock.json
  server/server.js
Labels: enhancement

#31 Front-End Queries - User Data
  client/src/pages/Login.js
  client/src/pages/Profile.js
  client/src/pages/Signup.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
Labels: new feature

#34 Feature/blog
  client/package.json
  client/src/App.js
  client/src/components/Blog/AllPosts.js
  client/src/components/Blog/QuestionsList.jsx
  client/src/components/Blog/SinglePost.js
  client/src/components/Blog/SingleQuestion.jsx
  client/src/pages/Blog.js
  client/src/pages/Login.js
  client/src/pages/Profile.js
  client/src/pages/Quiz.js
  client/src/pages/Signup.js
  client/src/pages/WritePost.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
Labels: enhancement

#36 Minor Changes
  client/src/utils/mutations.js
  server/models/Feedback.js
Labels: bug

#35 Added Seeding for One Prompt
  server/models/User.js
  server/seeders/feedbackSeeds.json
  server/seeders/seeds.js
Labels: enhancement

#37 Feature/blog
  client/package-lock.json
  client/src/App.css
  client/src/App.js
  client/src/components/Blog/AllPosts.js
  client/src/components/Blog/Comment.js
  client/src/components/Blog/SinglePost.js
  client/src/components/SinglePrompt/Comment.js
  client/src/components/SinglePrompt/SinglePrompt.js
  client/src/components/SinglePrompt/SolutionForm.js
  client/src/pages/Blog.js
  client/src/pages/Login.js
  client/src/pages/Prompt.js
  client/src/pages/Signup.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  package-lock.json
  server/package-lock.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/utils/auth.js
Labels: new feature

#38 Adjusted the interview to work w/o context
  server/schemas/resolvers.js
Labels: bug

#39 SIGNUP
  package.json
  server/schemas/resolvers.js
  server/utils/auth.js
Labels: enhancement

#40 Minor adjustment to schema
  server/models/InterviewInfo.js
Labels: bug

#41 Another minor fix
  server/schemas/typeDefs.js
Labels: bug

#42 Auth changes
  client/src/components/Navbar/Navbar.js
  client/src/pages/Blog.js
  client/src/pages/Profile.js
  client/src/pages/Prompt.js
  client/src/pages/Quiz.js
Labels: enhancement

#44 Added new fields to typeDefs
  server/schemas/typeDefs.js
Labels: enhancement

#46 Feature/blog page
  client/src/App.js
  client/src/pages/InterviewFeed.js
  client/src/pages/Profile.js
  client/src/pages/Signup.js
  client/src/pages/WritePost.js
  client/src/utils/queries.js
  server/schemas/resolvers.js
Labels: enhancement

#48 Added All Queries and Mutations
  client/package-lock.json
  client/package.json
  client/src/pages/Prompt.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/package-lock.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#49 Fixed Apollo Connection Issue
  client/package.json
  client/src/App.js
Labels: bug

#50 Feature/profile working
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Blog/AllPosts.js
  client/src/components/Blog/Comment.js
  client/src/components/Blog/SinglePost.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Profile/SolutionsUser.js
  client/src/components/SinglePrompt/Comment.js
  client/src/pages/Profile.js
  client/src/utils/queries.js
Labels: enhancement

#51 Expanded Feedback Params
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#52 Feature/profile working
  client/src/App.css
  client/src/components/Algorithm/Algorithm.jsx
  client/src/components/Interviews/AllInterviews.js
  client/src/components/Profile/CompletedPrompts.js
  client/src/components/Profile/InterviewsUser.js
  client/src/components/Profile/SolutionsUser.js
  client/src/components/Profile/TodoPrompts.js
  client/src/components/SinglePrompt/Comment.js
  client/src/components/SinglePrompt/SolutionForm.js
  client/src/pages/Interviews.js
  client/src/pages/Profile.js
  client/src/pages/WritePost.js
  client/src/utils/queries.js
  server/models/Solution.js
Labels: enhancement

#54 Feature/profile working
  client/src/App.css
  client/src/components/Interviews/AllUserInterviews.js
  client/src/components/Interviews/SingleInterview.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Profile/CompletedPrompts.js
  client/src/components/Profile/InterviewsUser.js
  client/src/components/Profile/SolutionsUser.js
  client/src/components/Profile/Stats.js
  client/src/components/Profile/TodoPrompts.js
  client/src/components/SinglePrompt/Comment.js
  client/src/pages/Home.js
  client/src/pages/Profile.js
  client/src/pages/WritePost.js
Labels: enhancement

#55 cleaned up interview component, no routes available to logged out users
  client/src/App.css
  client/src/components/Interviews/SingleInterview.js
  client/src/components/Profile/CompletedPrompts.js
  client/src/components/Profile/InterviewsUser.js
  client/src/components/Profile/SolutionsUser.js
  client/src/pages/Profile.js
  client/src/pages/WritePost.js
Labels: cleaning

#57 Seeding Database
  server/seeders/interviewInfoSeeds.json
  server/seeders/seeds.js
  server/seeders/solutionSeeds.json
Labels: enhancement

#59 Feature/profile working
  README.md
  client/src/assets/DEMO.png
  client/src/components/Blog/SinglePost.js
  client/src/components/Interviews/SingleInterview.js
  client/src/components/Navbar/Navbar.js
  client/src/index.css
  client/src/pages/WritePost.js
Labels: enhancement, cleaning

#60 Added Prompt
  server/schemas/resolvers.js
  server/seeders/seeds.js
Labels: enhancement

#61 Feature/blog page
  client/src/components/Interviews/SingleInterview.js
  client/src/pages/Interviews.js
Labels: enhancement
